# config file for netlify to build the project

#build folder to publish + build command
[build]
  publish = "public"
  command = "yarn build"

#build tool versions
[build.environment]
  YARN_VERSION = "1.5.1"
  YARN_FLAGS = "--no-ignore-optional"
